dist: xenial
language: ruby
rvm: 2.5.3
gemfile: Gemfile
services:
  - postgresql
script: bundle exec rake test
before_install:
  - psql -c 'CREATE DATABASE pgsync_test1;' -U postgres
  - psql -c 'CREATE DATABASE pgsync_test2;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
